###
POST http://localhost:8080/categories
Content-Type: application/json

{
  "name": "Category 2 name"
}

###
POST http://localhost:8080/products
Content-Type: application/json

{
  "categoryId": 1,
  "title": "Product title",
  "price": 50
}

###
PUT http://localhost:8080/products/1
Content-Type: application/json

{
  "categoryId": 2,
  "title": "New Product title",
  "price": 150
}
